interface IEntrega {
    id_age: number,
    status_age: string,
    data_age: string,
    horario_age: string,
    desc_age: string,
    onde_age: string,
    assinatura_age: string,
    tb_funcionarios_id_fun: number,
    tb_condominios_id_con: number,
    tb_local_secundario_id_loc: number,
    tb_escritorios_id_esc: number,
    id_con: number,
    nome_con: string,
    endereco_con: string,
    bairro_con: string,
    cidade_con: string,
    estado_con: string,
    telefone_con: string,
    resp_con: string,
    id_fun: number,
    nome_fun: string,
    nome_local: string,
    endereco_local: string
}